### PR TITLE
The Sign Up page

### PR DESCRIPTION
**Pull request by tareqabufayad**
### Mint Sign Up page
We used these techniques to build the page:

- HTML5 
- CSS3
- HTML Form tags
- HTML copyright entity

### CODE REVIEW

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
# Status: Changes requested :red_circle: 

## Hello @tariqabufayad and @martinnajjar12 :wave: 

## Your page looks awesome, it's hard to see the differences between yours and the original :smile: 

## You guys ALMOST did it, I swear I was almost approving it, but we still need to fix something, alright?

### Form

- [ ] Your 'Create Account' button needs to have a type of `submit`, it's currently 'typeless' :sweat_smile: 

## Kindly make the requested changes and submit for another review, please :pray: 

## I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Comment by martinnajjar12** [comment]
@MuriloRoque Thanks a lot for your review.
Now everything is OK.

**Review by kubilaycaglayan — APPROVED** [review]
Hello Team 👋 
Status: Project Approved 🟢 

Amazing job, your page looks really great!

With all my respect...

**Comment by tareqabufayad** [comment]
> Hello Team 👋
> Status: Project Approved 🟢
> 
> Amazing job, your page looks really great!
> 
> With all my respect...

Thank you for feedback and for your time to review.

**Pull request merged**
